export default [
    {
        name: "我的报销",
        icon: require("@/assets/img/labelicon1.png"),
        hovericon: require("@/assets/img/labelicon1-1.png"),
        active: 0,
        url: 'MineAccount'
    }, {
        name: "报销管理",
        icon: require("@/assets/img/labelicon3.png"),
        hovericon: require("@/assets/img/labelicon3-1.png"),
        active: 0,
        url: 'AccountManage'
    }, {
        name: "采购任务",
        icon: require("@/assets/img/labelicon2.png"),
        hovericon: require("@/assets/img/labelicon2-1.png"),
        active: 0,
        url: 'BuyTask'
    }, {
        name: "审批",
        icon: require("@/assets/img/labelicon4.png"),
        hovericon: require("@/assets/img/labelicon4-1.png"),
        active: 0,
        url: 'Approval'
    }, {
        name: "统计",
        icon: require("@/assets/img/labelicon5.png"),
        hovericon: require("@/assets/img/labelicon5-1.png"),
        active: 0,
    }, {
        name: "客户",
        icon: require("@/assets/img/labelicon6.png"),
        hovericon: require("@/assets/img/labelicon6-1.png"),
        active: 0,
    }, {
        name: "供应商管理",
        icon: require("@/assets/img/labelicon9.png"),
        hovericon: require("@/assets/img/labelicon9-1.png"),
        active: 0,
        url: 'Suply'
    }, {
        name: "项目管理",
        icon: require("@/assets/img/labelicon7.png"),
        hovericon: require("@/assets/img/labelicon7-1.png"),
        active: 0,
        url: 'ProjectManage'
    }, {
        name: "我的工作",
        icon: require("@/assets/img/labelicon8.png"),
        hovericon: require("@/assets/img/labelicon8-1.png"),
        active: 0,
        url: 'MineWork'
    }, {
        name: "入库",
        icon: require("@/assets/img/labelicon10.png"),
        hovericon: require("@/assets/img/labelicon10-1.png"),
        active: 0,
        url: 'InStorage'
    }, {
        name: "出库",
        icon: require("@/assets/img/labelicon11.png"),
        hovericon: require("@/assets/img/labelicon11-1.png"),
        active: 0,
        url: 'OutStorage'
    }, {
        name: "主营票款",
        icon: require("@/assets/img/labelicon14.png"),
        hovericon: require("@/assets/img/labelicon14-1.png"),
        active: 0,
        url: 'MainFare'
    }, {
        name: "发票管理",
        icon: require("@/assets/img/labelicon12.png"),
        hovericon: require("@/assets/img/labelicon12-1.png"),
        active: 0,
        url: 'BillManage'
    }, {
        name: "参数管理",
        icon: require("@/assets/img/labelicon13.png"),
        hovericon: require("@/assets/img/labelicon13-1.png"),
        active: 0,
        url: 'ParamManage'
    }
]